### ISSUE TITLE
Failure in javascript domain with check command

### ISSUE THREAD

**Issue by ghislain-bernard** [CheckiO/checkio-client#12]
I have a failure with checkio command in javascript domain :
```
$ checkio --domain=js run multiply-intro --check

Start checking...

['err', 'Traceback (most recent call last):\n  File "/opt/project/runners/ucheck/centertasks/uch.py", line 22, in <module>\n    S.LISTENERS[S.ON_CONNECT](run_data)\n  File "/opt/project/runners/ucheck/centertasks/checkio/referees/io.py", line 48, in on_ready\n    {\nKeyError: \'js\'\n', 'uch']
['error', 'ErrUchIsDown']
```

But everything is fine in python domain :
```
$ checkio --domain=py run multiply-intro --check

Start checking...

*** Basics ***
->[3, 2]
<-6
->[0, 1]
<-0
*** Extra ***
->[6, 3]
<-18
->[6, 7]
<-42

!!! Congratulation !!!

Link for checking solution of other users: https://py.checkio.org/mission/multiply-intro/publications/

Link for sharing solution: https://py.checkio.org/mission/multiply-intro/publications/add/
```
Here my config.ini :
```
$ cat ~/.checkio/config.ini 
[Main]
default_domain = js

[js_checkio]
executable = node
key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
solutions = /home/user/checkio-js

[py_checkio]
key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
solutions = /home/user/checkio-py
```

**Comment by oduvan** [comment]
thank you.

Please try to upgrade your client and try again

**Comment by ghislain-bernard** [comment]
After updated the client, I have the same message as #13.
I close this issue.
