### ISSUE TITLE
Open command fails

### ISSUE THREAD

**Issue by henioStraszny** [CheckiO/checkio-client#18]
Open command fails, perhaps I need some environment variable?

```console
 $  checkio open multiply-intro
Traceback (most recent call last):
  File "/home/henio/.local/bin/checkio", line 11, in <module>
    sys.exit(main())
  File "/home/henio/.local/lib/python3.6/site-packages/checkio_client/runner.py", line 217, in main
    getattr(module, func_name)(args)
  File "/home/henio/.local/lib/python3.6/site-packages/checkio_client/actions/open.py", line 26, in main
    open_editor([domain_data['editor'], filename])
NameError: name 'open_editor' is not defined
```

**Comment by oduvan** [comment]
fixed in the next release
