### ISSUE TITLE
exception when using "check" on some missions

### ISSUE THREAD

**Issue by robreiss** [CheckiO/checkio-client#27]
running the command:

checkio check Incinerator/the_warriors.py

causes an exception in the checkio-client (exception trace is below)

This exception occurs on many of the missions in the "Incinerator" area.

What I believe is happening is that a call to the "ucheck" url returns testing data. That data has an unexpected format. Some of the "in" blocks have a fourth element that is "None". The client believes the "in" blocks should have only three elements or if it has a fourth it should be iterable. 

Is the code for "ucheck" available on github? Which repository?

I will produce a PR that works around the exception. Not sure what the web interface is doing to get around this problem.

```
Traceback (most recent call last):
  File "/Users/x/opt/anaconda3/bin/checkio", line 8, in <module>
    sys.exit(main())
  File "/Users/x/opt/anaconda3/lib/python3.9/site-packages/checkio_client/runner.py", line 229, in main
    getattr(module, func_name)(args)
  File "/Users/x/opt/anaconda3/lib/python3.9/site-packages/checkio_client/actions/check.py", line 23, in api_call
    return globals()[func_name + '_' + conf.default_domain_data['game']](*args, **kwargs)
  File "/Users/x/opt/anaconda3/lib/python3.9/site-packages/checkio_client/actions/check.py", line 234, in main_run_cio
    return main(args)
  File "/Users/x/opt/anaconda3/lib/python3.9/site-packages/checkio_client/actions/check.py", line 23, in api_call
    return globals()[func_name + '_' + conf.default_domain_data['game']](*args, **kwargs)
  File "/Users/x/opt/anaconda3/lib/python3.9/site-packages/checkio_client/actions/check.py", line 97, in main_check_cio
    if len(block) >= 4 and 'assert' in block[3]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by oduvan** [comment]
works. thanks for the fix
